package com.ransomlab.models;

import java.util.ArrayList;
import java.util.List;

public class AttackRepository {
    public static List<Attack> getAll() {
        List<Attack> list = new ArrayList<>();

        list.add(new Attack("wannacry", "WannaCry", 2017, "#FF2D55", "EternalBlue SMB Worm", "Network · Unpatched SMBv1", "~$4 Billion", "200,000+ across 150 countries", "$300–$600 BTC", "AES-128 + RSA-2048", "Lazarus Group (North Korea)", "Caused by the failure of organizations to apply the critical MS17-010 Windows security patch, leaving the legacy SMBv1 file-sharing protocol exposed to the leaked NSA EternalBlue exploit.", "Exploited the NSA's stolen EternalBlue exploit targeting unpatched Windows SMBv1. Self-propagating worm that spread globally in hours.", new String[]{"Scanning for SMBv1 port 445...", "Sending EternalBlue exploit payload...", "Encrypting files with AES-128..."}, false));
        list.add(new Attack("notpetya", "NotPetya", 2017, "#FF6B35", "MBR Wiper / Destroyer", "Supply Chain · MEDoc Update", "$10+ Billion", "Maersk, Merck, Rosneft, FedEx", "N/A — Wiper, no recovery", "Salsa20 + RSA-2048", "Sandworm / Russian GRU", "Initiated through a compromised software supply chain. Attackers hacked the update servers of M.E.Doc and pushed a malicious backdoor.", "Disguised as ransomware but a destructive wiper. Overwrites MBR permanently — no decryption possible.", new String[]{"MEDoc update server compromised...", "Overwriting Master Boot Record (MBR)...", "Scheduling forced reboot — system destroyed..."}, true));
        list.add(new Attack("revil", "REvil / Sodinokibi", 2019, "#FF9A00", "RaaS Double Extortion", "RDP Brute Force", "$200+ Million", "Kaseya VSA, JBS Foods", "$70M BTC (Kaseya demand)", "AES-256-CBC + Curve25519", "Unknown (Russia-linked)", "Typically occurred because organizations left Remote Desktop Protocol (RDP) ports open to the public internet with weak passwords.", "One of the most sophisticated Ransomware-as-a-Service operations. Pioneered double extortion.", new String[]{"Gaining initial access via RDP...", "Exfiltrating sensitive data via SFTP...", "Encrypting with AES-256-CBC..."}, false));
        list.add(new Attack("lockbit", "LockBit", 2019, "#FFD700", "Fastest Encryptor", "Phishing · Exposed RDP", "$91+ Million (US alone)", "Boeing, ION Group", "$50K–$50M per victim", "AES-256 + RSA-2048", "LockBit Gang", "Facilitated by a vast network of 'affiliates' who exploited unpatched firewalls and bought stolen credentials.", "The most prolific ransomware gang of 2022-2023. Known for extreme speed.", new String[]{"Affiliate gaining RDP/VPN access...", "Launching multi-threaded encryptor...", "Posting victim on LockBit leak site..."}, false));
        list.add(new Attack("ryuk", "Ryuk", 2018, "#AAFF00", "Big Game Hunting", "Spear Phishing", "$150+ Million", "Universal Health Services", "$100K–$12.5M per target", "RSA-4096 + AES-256", "Wizard Spider", "Almost always started with human error: an employee opening a malicious email attachment that unknowingly installed a botnet.", "Targets large enterprises for maximum ransom. Delivered via TrickBot or Emotet.", new String[]{"Emotet/TrickBot gaining foothold...", "Deploying Ryuk to all domain hosts...", "Encrypting with RSA-4096 + AES-256..."}, false));
        list.add(new Attack("kaseya", "Kaseya VSA", 2021, "#00FF88", "Supply Chain", "Zero-day in Kaseya", "$70M demanded", "1,500+ businesses", "$70M BTC", "AES-256 + RSA-2048", "REvil / Sodinokibi", "Happened due to a zero-day vulnerability in Kaseya's VSA server software. No patch was available.", "REvil exploited a zero-day auth bypass in Kaseya VSA remote management software.", new String[]{"Exploiting Kaseya VSA zero-day...", "Pushing ransomware to 1,500+ endpoints...", "Demanding $70M for universal decryptor..."}, false));
        list.add(new Attack("jbs", "JBS Foods", 2021, "#00FFD4", "Critical Infrastructure", "Compromised credentials", "$11 Million paid", "Largest global meat processor", "$11M USD paid", "AES-256-CBC", "REvil", "Occurred when attackers compromised weak VPN credentials, and the network lacked internal segmentation.", "REvil attacked JBS shutting down plants across USA, Australia, and Canada.", new String[]{"Compromised JBS VPN credentials...", "Shutting down plant control servers...", "Paying $11M ransom for decryptors..."}, false));
        list.add(new Attack("colonial", "Colonial Pipeline", 2021, "#00AAFF", "Critical Infrastructure", "Compromised VPN password", "$4.4M paid", "45% of US East Coast fuel", "$4.4M BTC", "ChaCha20 + RSA-4096", "DarkSide", "Caused by an old, inactive employee VPN account left enabled without MFA.", "DarkSide hit Colonial Pipeline, causing fuel shortages across the US East Coast.", new String[]{"Breaching via leaked VPN password...", "Exfiltrating 100GB of business data...", "Colonial shuts 5,500-mile pipeline..."}, false));
        list.add(new Attack("blackbasta", "Black Basta", 2022, "#4488FF", "Double Extortion", "QakBot · Phishing", "$100+ Million", "ABB, Capita", "$500K–$2M average", "ChaCha20 + RSA-4096", "Former Conti members", "Typically initiated through QakBot malware delivered via highly convincing phishing emails.", "Emerged after Conti disbanded. Uses QakBot for initial access.", new String[]{"QakBot phishing email delivered...", "Deploying Black Basta to all hosts...", "Data posted on Black Basta leak site..."}, false));
        list.add(new Attack("akira", "Akira", 2023, "#AA44FF", "Modern RaaS", "Compromised Cisco VPN", "$42 Million", "Stanford, Nissan", "$200K–$4M per victim", "AES-256-CTR + RSA-4096", "Unknown", "Happened by exploiting vulnerable Cisco VPN endpoints that organizations failed to update.", "Emerged in 2023 targeting SMBs and enterprises. Exploits Cisco VPN vulnerabilities.", new String[]{"Exploiting Cisco VPN...", "Establishing SSH tunnel for C2...", "Files renamed with .akira extension..."}, false));

        return list;
    }
}